---
driver:
  name: docker
  hostname: kibana.ci.local
  use_sudo: false

provisioner:
  name: salt_solo
  salt_install: bootstrap
  salt_bootstrap_url: https://bootstrap.saltstack.com
  salt_version: latest
  require_chef: false
  log_level: error
  formula: kibana
  grains:
    noservices: True
  state_top:
    base:
      "*":
        - linux
        - kibana
  pillars:
    top.sls:
      base:
        "*":
          - kibana
          - kibana_ubuntu_repo
  pillars-from-files:
    kibana_ubuntu_repo.sls: tests/pillar/kibana_ubuntu_repo.sls
  dependencies:
    - name: linux
      repo: git
      source: https://github.com/salt-formulas/salt-formula-linux.git

verifier:
  name: inspec
  sudo: true

platforms:
  - name: 'ubuntu-xenial'
    driver_config:
      platform: ubuntu
      provision_command:
        - apt-get update && apt-get install -y locales git && locale-gen en_US.UTF-8


suites:
  - name: kibana_server
    provisioner:
      pillars-from-files:
        kibana.sls: tests/pillar/kibana_server.sls
